### ISSUE TITLE
tensorflow feature extraction

### ISSUE THREAD

**Issue by johnkorn** [sladomic/Face-Recognition#1]
Hi!
How do you extract features from TF inception5h model? what tensor/layer do you use?
Could you share some related code?

**Comment by sladomic** [comment]
Hi

We will release the code in the next days. I will then update the Play Store Description with a link to the Open Source GitHub project.

We use the avgpool:0 layer because the last layer would give us the prediction/classification. But we just want the features which are assumed to be found a few layers before.

As we use the C++ API we are limited with TensorFlow functions. To extract the features we used this code <https://github.com/miyosuda/TensorFlowAndroidDemo/blob/master/jni-build/jni/tensorflow_jni.cc> and modified it for our needs.

But if you can wait, you will be able to check out the full code soon.

Best regards
Michael

**Comment by sladomic** [comment]
Hi

The repository is now available open source.

https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning

This one will be deleted.

Thanks,
Michael
